class NodeModelTypes:
    Gemini = 'gemini'
    CombineText = 'combine_text'
    UserInput = 'user_input'
    WebScraper = 'web_scraper'
    FileReader = 'file_reader'
    ResumeAnalysis = 'resume_analysis'
    SummarizerNode = 'summarizer'
    ZipReaderNode = 'zip_reader'
    RedditBotNode = 'reddit_bot'
    CompanyEnrichmentNode = 'company_enrichment'
    YouTubeCommentsRetriever = 'yt_comments'
    # File processing
    SheetWriterNode = 'sheet_writer'
    ScoringNode = 'scoring'
    GeminiRAG = 'gemini_rag'
